### PR TITLE
♻️ Remove download transform

### PR DESCRIPTION
**Pull request by falexwolf**

### CODE REVIEW

**Comment by falexwolf** [comment]
I fear nextflow is down again? 🤔 

This was flaky before, wasn't it?

**Comment by falexwolf** [comment]
@Zethson - do you understand why the builds are failing now?

**Comment by Zethson** [comment]
On mobile, but be careful with changing the nextflow run ID. It only allows specific formats. The nextflow run likely fails and you don't see that in the error log

**Comment by falexwolf** [comment]
Thanks, Lukas! Right, I might have introduced some braces there... trying to fix.

**Pull request merged**
